packages:
  - apps/*
  - apps/web/*
  - apps/server/*
  - packages/*
  - scripts/*

catalog:
  '@element-plus/icons-vue': ^2.3.2
  '@koa/cors': ^3.3.0
  '@koa/router': ^14.0.0
  '@types/glob': ^7.2.0
  '@types/koa': ^2.13.4
  '@types/koa-bodyparser': ^4.3.7
  '@types/koa-router': ^7.4.4
  '@vitejs/plugin-vue': ^6.0.1
  axios: ^0.27.2
  compressing: ^1.6.0
  cross-env: 7.0.3
  dayjs: ^1.11.3
  dotenv: ^16.0.1
  echarts: ^5.3.3
  element-plus: ^2.11.3
  eslint: ^9.36.0
  fs-extra: ^10.1.0
  koa: ^2.13.4
  koa-body: ^5.0.0
  koa-bodyparser: ^4.3.0
  mongoose: ^6.4.0
  pinia: ^3.0.3
  prettier: ^3.6.2
  qrcode.vue: ^3.3.3
  sass: ^1.32.7
  sass-loader: ^12.0.0
  ts-node-dev: ^2.0.0
  turbo: ^2.5.6
  typescript: ^4.7.4
  uuid: ^8.3.2
  vite: ^7.1.7
  vue: ^3.5.21
  vue-router: ^4.5.1
  glob: ^11.0.3
  lodash-es: ^4.17.21
  qs: ^6.14.0
  '@dotenvx/dotenvx': ^1.51.1
  rollup-plugin-visualizer: ^6.0.4
  tsup: ^8.5.0
  unplugin-auto-import: ^20.2.0
  unplugin-vue-components: ^29.1.0
